apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi
spec:
  selector:
    matchLabels:
      app: testapi
  replicas: 1
  template:
    metadata:
      labels:
        app: testapi
    spec:
      containers:
      - name: testapi
        image: gcr.io/data-shark-378612/testapi:v1
        ports:
        - containerPort: 8080
