apiVersion: apps/v1
kind: Deployment
metadata:
  name: nftapidep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nftapi
  template:
    metadata:
      labels:
        app: nftapi
    spec:
      containers:
      - name: nftapi-app
        image: gcr.io/Data-Shark/test_api:v1
        ports:
        - containerPort: 8501
